openreachtech/furo-core

lib/client/BaseGraphqlCapsule.js

🧩 Fix type of `GraphqlResponseError`

---

lib/client/BaseGraphqlCapsule.js
tests/__tests__/lib/client/BaseGraphqlCapsule.js

⚒️ Define `BaseGraphqlCapsule#get:content`

---

lib/client/BaseGraphqlCapsule.js
tests/__tests__/lib/client/BaseGraphqlCapsule.js

⚒️ Define `BaseGraphqlCapsule#get:errors`

---

lib/client/BaseGraphqlCapsule.js

💪 Update members of `BaseGraphqlCapsule` with `#get:content`

---

lib/client/BaseGraphqlCapsule.js

💪 Update members of `BaseGraphqlCapsule` with `#get:errors`

---

lib/client/BaseGraphqlCapsule.js
tests/__tests__/lib/client/BaseGraphqlCapsule.js

✅️ Enhance `BaseGraphqlCapsule` with `#get:content` and `#get:errors`

---

package-lock.json
package.json

⚙️ Update package version to `1.8.0`

---

lib/client/BaseGraphqlCapsule.js
package-lock.json
package.json
tests/__tests__/lib/client/BaseGraphqlCapsule.js

* Close #19
* Merge to `main` after publish

Release > Main [minor] `1.8.0`

---

index.js

🧹 Rearrange export order in `index.js`

---

lib/tools/ProgressHttpFetcher.js
tests/__tests__/lib/tools/ProgressHttpFetcher.js

⚒️ Define `ProgressHttpFetcher.isBodyRequiredMethod()`

---

lib/client/BaseGraphqlPayload.js
tests/__tests__/lib/client/BaseGraphqlPayload.js

🐛 Fix `BaseGraphqlPayload#createMergedHeaders()`

---

lib/tools/ProgressHttpFetcher.js

🧹 Rename `isBodyHandlingMethod` to `isBodyRequiredMethod` in `ProgressHttpFetcher.createFormDataBody()`

---

lib/client/restfulapi/constants.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiPayload.js

🧩 Tidy up type errors in test for `BaseRestfulApiPayload`

---

lib/client/restfulapi/BaseRestfulApiCapsule.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiCapsule.js

⚒️ Declare `BaseRestfulApiCapsule`

---

lib/client/graphql/BaseGraphqlSubscriber.js
types/furo.d.ts

🧩 Define `GraphqlSubscribeRequestArgs` type in `BaseGraphqlSubscriber`

---

types/furo.d.ts
types/graphql.d.ts

🧩 Define `GraphqlType` namespace in separated file

---

types/furo.d.ts
types/restfulapi.d.ts

🧩 Define `RestfulApiType`

---

tests/__tests__/lib/client/restfulapi/BaseRestfulApiLauncher.js

🧩 Fix arguments to pass `BaseRestfulApiPayload.create()` in test for `BaseRestfulApiLauncher`

---

app/contexts/UploadImagePageGraphqlSubmitter.js
app/graphql/clients/BaseAppGraphqlLauncher.js
app/graphql/clients/BaseAppGraphqlPayload.js
app/graphql/clients/BaseAppSubscriptionGraphqlPayload.js
lib/client/graphql/BaseGraphqlCapsule.js
lib/client/graphql/BaseGraphqlLauncher.js
lib/client/graphql/BaseGraphqlSubscriber.js
lib/client/graphql/BaseSubscriptionGraphqlCapsule.js
lib/client/graphql/BaseSubscriptionGraphqlPayload.js
lib/client/graphql/SubscriptionConnector.js
pages/client/company-sponsors.html
pages/client/curriculums.html
pages/client/sign-up.html
tests/__tests__/lib/client/graphql/BaseGraphqlLauncher.js
tests/__tests__/lib/client/graphql/BaseGraphqlPayload.js
types/graphql.d.ts

🧩 Replace namespace for GraphQL types from `furo` to `GraphqlType`

---

types/furo.d.ts

🦵 Kick out duplicated types concerning GraphQL from `furo.d.ts`

---

app/contexts/UploadImagePageGraphqlSubmitter.js

🧩 Fix JSDoc in `UploadImagePageGraphqlSubmitter`

---

types/restfulapi.d.ts

🧩 Fix exported types in `restfulapi.d.ts`

---

lib/tools/DerivedClassNameGenerator.js
tests/__tests__/lib/tools/DerivedClassNameGenerator.js

⚒️ Declare `DerivedClassNameGenerator`

---

lib/tools/derived-ctor-registry/concretes/RestMethodRestfulApiPayloadDerivedCtorRegistry.js
tests/__tests__/lib/tools/derived-ctor-registry/concretes/RestMethodRestfulApiPayloadDerivedCtorRegistry.js

⚒️ Declare `RestMethodRestfulApiPayloadDerivedCtorRegistry`

---

lib/client/restfulapi/BaseRestfulApiPayload.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiPayload.js

⚒️ Enhance `BaseRestfulApiPayload` with decorative builder pattern

---

lib/client/restfulapi/BaseRestfulApiLauncher.js
lib/client/restfulapi/BaseRestfulApiPayload.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiPayload.js

✅️ Retake RESTful API cilent handling `BASE_URL` with fixed pathname

---

lib/client/restfulapi/BaseRestfulApiLauncher.js
types/restfulapi.d.ts

🦵 Kick out unnecessary type from `restfulapi.d.ts`

---

app/graphql/clients/BaseAppGraphqlCapsule.js
app/graphql/clients/BaseAppGraphqlLauncher.js
app/graphql/clients/BaseAppGraphqlPayload.js

🧹 Fix JSDoc of base app GraphQL client classes

---

lib/client/restfulapi/renchan/BaseRenchanRestfulApiCapsule.js
lib/client/restfulapi/renchan/BaseRenchanRestfulApiLauncher.js
lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiCapsule.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiLauncher.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js

* Close
#123
#124 
#125
* Declare stub classes

⚒️ Implement `renchan` derived RESTful API client as stub

---

lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js

⚒️ Fulfill `BaseRenchanRestfulApiPayload` by members cut from `BaseAppRenchanRestfulApiPayload`

---

lib/client/restfulapi/BaseRestfulApiCapsule.js

🧩 Update JSDoc in `BaseRestfulApiCapsule`

---

lib/client/restfulapi/BaseRestfulApiCapsule.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiCapsule.js

⚒️ Define `BaseRestfulApiCapsule#generateResultError()`

---

tests/__tests__/lib/client/restfulapi/BaseRestfulApiCapsule.js

🧩 Fix type errors in test for `BaseRestrulApiCapsule.create()`

---

lib/tools/PathnameBuilder.js
tests/__tests__/lib/tools/PathnameBuilder.js

⚒️ Declare `PathnameBuilder`

---

lib/client/restfulapi/BaseRestfulApiPayload.js
lib/tools/PathnameBuilder.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiPayload.js
tests/__tests__/lib/tools/PathnameBuilder.js

✅️ Retake `BaseRestfulApiPayload` with `PathnameBuilder`

---

lib/client/restfulapi/BaseRestfulApiPayload.js

🐛 Fix import path in `BaseRestfulApiPayload`

---

app/restfulapi/renchan/BaseAppRenchanRestfulApiCapsule.js
app/restfulapi/renchan/BaseAppRenchanRestfulApiLauncher.js
app/restfulapi/renchan/BaseAppRenchanRestfulApiPayload.js
tests/__tests__/app/restfulapi/renchan/BaseAppRenchanRestfulApiCapsule.js
tests/__tests__/app/restfulapi/renchan/BaseAppRenchanRestfulApiLauncher.js
tests/__tests__/app/restfulapi/renchan/BaseAppRenchanRestfulApiPayload.js

✅️ Declare base app classes for demo of RESTful API cilent

---

app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiCapsule.js
app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiLauncher.js
app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiPayload.js
tests/__tests__/app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiCapsule.js
tests/__tests__/app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiLauncher.js
tests/__tests__/app/restfulapi/renchan/get/alphaExternalCallbackSuccess/AlphaExternalCallbackSuccessGetRenchanRestfulApiPayload.js

* Close #168
* Declare `AlphaExternalCallbackSuccessGetRenchanRestfulApiPayload`
* Declare `AlphaExternalCallbackSuccessGetRenchanRestfulApiCapsule`
* Declare `AlphaExternalCallbackSuccessGetRenchanRestfulApiLauncher`

⚒️ Implement `AlphaExternalCallbackSuccess` RESTful API client

---

app/domClerk/BetaExternalCallbackSuccessFormElementClerk.js
tests/__tests__/app/domClerk/BetaExternalCallbackSuccessFormElementClerk.js

 ⚒️ Declare `BetaExternalCallbackSuccessFormElementClerk` for `<form method="POST">`

---

index.html
pages/client/restfulapi.html

* Close #179
* Build demo page for RESTful API client
* Add link to RESTful API demo page in `index.html`

🏗️ Build demo page of RESTful API client

---

lib/tools/response-body-parser/BaseResponseBodyParser.js
tests/__tests__/lib/tools/response-body-parser/BaseResponseBodyParser.js

⚒️ Declare `BaseResponseBodyParser`

---

lib/tools/response-body-parser/concretes/JsonResponseBodyParser.js
tests/__tests__/lib/tools/response-body-parser/concretes/JsonResponseBodyParser.js

⚒️ Declare `JsonResponseBodyParser`

---

lib/tools/response-body-parser/BaseResponseBodyParser.js
lib/tools/response-body-parser/concretes/JsonResponseBodyParser.js
tests/__tests__/lib/tools/response-body-parser/BaseResponseBodyParser.js
tests/__tests__/lib/tools/response-body-parser/concretes/JsonResponseBodyParser.js

✅️ Implement `ResponseBodyParser` family

---

lib/client/restfulapi/BaseRestfulApiCapsule.js
lib/client/restfulapi/BaseRestfulApiLauncher.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiCapsule.js
tests/__tests__/lib/client/restfulapi/BaseRestfulApiLauncher.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiCapsule.js

🧹 Tidy up JSDoc and `describe()` concerning JSON parse

---

tests/__tests__/app/domClerk/SignUpFormElementClerk.js

🧹 Tidy up test for `SignUpFormElementClerk`

---

index.html

🐛 Fix format error in `index.html`

---

index.html
lib/client/restfulapi/BaseRestfulApiLauncher.js
tests/__tests__/app/domClerk/SignUpFormElementClerk.js

✅️ Tidy up aside code

---

index.html

🏗️ Add `sign-in` UI in `index.html`

---

tests/__tests__/lib/client/graphql/BaseGraphqlCapsule.js

🧩 Fix type errors in test for `BaseGraphqlCapsule`

---

pages/client/sign-up.html
tests/__tests__/lib/client/graphql/BaseGraphqlCapsule.js
tests/__tests__/lib/client/graphql/BaseGraphqlPayload.js
tests/__tests__/lib/validator/ValueHashValidator.js

🦵 Kick out actual username

---

lib/client/restfulapi/BaseRestfulApiLauncher.js

🧩 Fix JSDoc for `BaseRestfulApiLauncher.createPayload()`

---

lib/dom/FormElementInspector.js
tests/__tests__/lib/dom/FormElementInspector.js

* Close #235
* All members of `FormElementClerk` cloned form `BaseFormElementClerk`
* Fulfilled test for two members

⚒️ Declare `FormElementClerk`

---

lib/client/graphql/BaseSubscriptionGraphqlCapsule.js

* Close #240 
* Close https://chiho-internal.openreach.tech/tasks/4430
* Update members of `BaseSubscriptionGraphqlCapsule` with `#get:errors`.

Update members of `BaseSubscriptionGraphqlCapsule` with `#get:errors`

---

lib/client/restfulapi/BaseRestfulApiLauncher.js
lib/client/restfulapi/BaseRestfulApiPayload.js
lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js
tests/__tests__/lib/client/restfulapi/renchan/BaseRenchanRestfulApiPayload.js

✅️ Fix type errors by feedback from `furo-nuxt`

---

package-lock.json
package.json

⚙️ Update package version to `1.10.0`
